unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf

set -s escape-time 0
set -g base-index 1
set -g status-interval 1
set -g renumber-windows on

# vi motions
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# style
set -g status-style "bg=black,fg=white"
setw -g window-status-style "bg=black,fg=white"
setw -g window-status-current-style "bg=green,fg=black"
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
set -g status-left " [#(basename #{session_path})] "
set -g status-left-length 200
set -g status-right "%H:%M %d-%m-%Y"
